spring.application.name=shortener-service
server.port=8080

spring.datasource.url=jdbc:h2:file:./shortener-service/src/main/resources/data/shortener-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
app.workspace.get-token-url=http://localhost:8081/api/tokens/
app.stats.stats-url=http://localhost:8082/api/stats/