spring.application.name=shortener-service
spring.profiles.active=dev


# Wenn keine gesetzt ist, nutzt er localhost (fuers Testen ohne Docker).
#spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/shortener-db}
#spring.datasource.username=${DB_USER:root}
#spring.datasource.password=${DB_PASS:s3cret}
#spring.jpa.hibernate.ddl-auto=update