spring.application.name=shortener-service
app.workspace.get-token-url=${WORKSPACE_API_URL}
app.stats.stats-url=${STATS_API_URL}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
