spring.application.name=workspace-service

server.port=8081

spring.datasource.url=jdbc:h2:file:./workspace-service/src/main/resources/data/workspace-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update