spring.application.name=client
#server.port= 8083
app.shortener.public-url=${SHORTENER_API_URL}
app.shortener.internal-url=${SHORTENER_INTERNAL_URL}
app.workspace.get-token-url=${WORKSPACE_API_URL}
app.stats.stats-url=${STATS_API_URL}
