spring.application.name=client
server.port=8083

app.shortener.public-url=http://localhost:8080/api/shortLinks/
app.workspace.get-token-url=http://localhost:8081/api/tokens/
app.stats.stats-url=http://localhost:8082/api/stats/
app.shortener.internal-url=http://localhost:8080/api/shortLinks
